version: '3'
services:
  app:
    build: .
    expose:
      - "8000"
    environment:
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Certificate.cer:/etc/letsencrypt/Certificate.cer
      - ./Private.key:/etc/letsencrypt/Private.key
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

volumes:
  certs:
  certs-data:
